# Generated by Django 5.1.3 on 2024-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
